language: python
matrix:
  include:
  - name: Python 3.6 on Linux
    os: linux
    python: 3.6
    env: DEPLOY=yes
  - name: Python 3.7 on Xenial Linux
    os: linux
    python: 3.7
    dist: xenial
    env: DEPLOY=yes
  - name: Python on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
    before_install:
    - pip3 install -U pip
  - name: Python on Windows
    os: windows
    language: shell
    before_install:
    - choco install python
    - pip3 install --user -U pip
    - pip3 install --user coveralls
    - pip3 install --user pytest
    env: PATH=/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:$PATH
install:
- pip3 install pytest pytest-asyncio pytest-cov
- pip3 install coveralls
- pip3 install Sphinx sphinxcontrib-napoleon sphinxcontrib-zopeext
- pip3 install -e .
script:
- pytest --cov=qulab --verbose
after_success:
- coveralls
deploy:
  provider: pypi
  user: feihoo87
  password:
    secure: Dxpts5YkzUpzAYJ5vKXxo94UmeXizkXQ3ABCme5TjZ5OGNUedQANaJ02fm+v57Mfufw6nzIuoF+IcfudR5H4EwXywn5cWmuhF0t7CgYOximtQap3VPdn0r0grbi+x6EwpUfcC7HP5GWz7hEC60tDX4JWItzNeV9/n4uSmtXlyrEFQ1UNqfPOm5nIEDsiOnJFOjBLbC25jnvxVNx17/JZhqe0DFgLFHMp3vlZCy6JBQ/0Hwb8A3DhL4fe50ZmpCL0xSavyR2RqgH4gHWENSa4ylO6zJ9sL3vVm4cuyvby57Geg+9VkARrkbsuwuhwYlKVLWWfaWKvVWa1Ftqi0WSjrxDu8Qv63Jv6HIr3xSjt1seK27IoFl5twxGKjplmLcFDI2fOmSk53etOUzjEAj+UclaP+dzKISxRrU36vsB7S8jgvNARiDbSQ6kYK/0xtYZ70fGRT2FtIXtpLh+XSKKSOPSQnfkMLXfp3iCS+E4Ecux6jpldxuB84V5K5z7d1bF1p7ZmfgV4llVWsgp6tHoj6gGUES/R37xGF4pA04wrffFO95ugwyC2VXJgx0ddk+Ef0UQYwvfpirzaqbqvi6ODJkzP6h6GbIzPu9WMxEtusKaL8rPBbj4KHTqrD4GaLiNbZ/4QYAb3IYxcPYU6xUrAYrHE7UVjSu90cPJvJGCphrU=
  on:
    branch: master
    tags: true
    condition: "$DEPLOY = yes"
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
