language: python
matrix:
  include:
  - name: Python 3.6 on Linux
    os: linux
    python: 3.6
    env: DEPLOY=yes
  - name: Python 3.7 on Xenial Linux
    os: linux
    python: 3.7
    dist: xenial
    env: DEPLOY=yes
  - name: Python 3.8 on Xenial Linux
    os: linux
    python: 3.8
    dist: xenial
    env: DEPLOY=yes
  - name: Python on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
    before_install:
    - pip3 install -U pip
  - name: Python on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.7.6
    - python -m pip install --user -U pip
    - python -m pip install --user coveralls
    - python -m pip install --user pytest pytest-asyncio pytest-cov
    - python -m pip install --user Sphinx sphinxcontrib-napoleon sphinxcontrib-zopeext
    - python -m pip install --user -r requirements.txt
    env: PATH=/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:$PATH
install:
- pip3 install -r requirements.txt
- pip3 install pytest pytest-asyncio pytest-cov
- pip3 install coveralls
- pip3 install Sphinx sphinxcontrib-napoleon sphinxcontrib-zopeext
- pip3 install -e .
script:
- pytest --cov=qurpc --verbose
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: fvSB4VGZYe/T3ykiKYHtBQoOzLXq26Z3PieyqlE9VzVA2P9Q1G+WRVRQ3lS3R7FluKEYyTjUsOU7o4/zKnoJB0oD0BdAaH5CAMc2bV8Ym2NiJgimueuUSTsrsKSDnz3UC3ciGoHKj6rujT6mdbjC0+RnfcwVPjVj9CTEJXV+rgPcccsdSR3ZRPUI7vWvSPvMb8c0LUZf46aGqS6eEAqTowWZe2czNpqSudZI8NW2AEahWD/JRT5luyS0wZ+ryP4VwCqWPV1TsAkbYpjcczyw4CKWFhhWktpkU/Q4IW5HjAVvW+2LQGHSV17oKq33jDSx5/qc1ke4Sn1UvWpAbFrKwIAwBKXzPIwjnJe4q7BKYr7iEl0iKIwU9+EB/Z5pEJz+mRbVVeCEEaef58bwsYCeDtojYuAKxCp9Xz4sND5X4GJmDHwx/DJIR6iE4pHKH7vaGHOw45w290Cyjkc00B7hudk7GJwGzdZwTrfoB3NVcaVDztEiS/NggGAWtbFj9GSRI+nzNL8idmRNlINzjEYRiCZFccq2T8/T8L/74LK9YHiLvY2kezo04QGVFY4ulIXhdbNarNKPBHJ+/DtFBzEq5fjE2pXjd7CAwUiz/h220jw1kreYlDVU64GuAdfruMl0xUIKB5BL2o3aklz1l+XykGHOLygjXAwwsayD9PQWg3s=
  on:
    branch: master
    tags: true
    condition: "$DEPLOY = yes"
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
