language: python
matrix:
  include:
  - name: Python 3.6 on Linux
    os: linux
    python: 3.6
    env: DEPLOY=yes
  - name: Python 3.7 on Xenial Linux
    os: linux
    python: 3.7
    dist: xenial
    env: DEPLOY=yes
  - name: Python on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
    before_install:
    - pip3 install -U pip
  - name: Python on Windows
    os: windows
    language: shell
    before_install:
    - choco install python
    - pip3 install --user -U pip
    - pip3 install --user coveralls
    - pip3 install --user pytest
    env: PATH=/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:$PATH
install:
- pip3 install pytest pytest-asyncio pytest-cov
- pip3 install coveralls
- pip3 install Sphinx sphinxcontrib-napoleon sphinxcontrib-zopeext
- pip3 install -e .
script:
- pytest --cov=qulab --verbose
after_success:
- coveralls
deploy:
  provider: pypi
  user: feihoo87
  password:
    secure: tI3bDo7I9b+ssIbRbZH021Soo3QTN95wzA/4tXUkBSIOrPJ54VXc6m9opzJXzBnq38+TwK29SgVpfWgCkWVzTCywAGI+88ILWNlpuoQkLRC1UsMBr4pB0iuPsgztRtYZl87gKlqzm6g+rJuHYt8roIr9idNytWyHBdqyprLZ9+gPZNMYqMLrnLYO1LEX2yiH6bviACno5zU3RJrP0vvo+DjCF/LY1xRyrc5APnEgT1mcW7PvOVC1Wy3tszy+iCK1wJK2Ts52LDOy+Br9bygOqcAa2OOYMgh2J0sev6gFbKXAoCnwwCL6y08VhLfLpRiQ38Vu3BjpNWuGSQ3+qdnDNp0YbCTNGIISwmDPhsoPbE7/4hOHZHRv8gu/7VbqRxPikHUPnPI3uCxc7KOy7qNE0Gf/37GSpVCZWlQ317ICLWk3DfHQ7CVVOb/6upWpG90IC8Sk07E28Uv8+m1CnOBXiXf/+6ozum21xpnWj2E9I3QKsq11jBTD/Q/6yrLWG7KDzns0s+XXJvyTLYI5zjgaYD+h6qlLHFXg2fb6eQ0kONs9pzMqgNKLhqn1r2EfYpodIj1b0PzmgUW74XEVz95aWIt2TmC4Xh5nwUgxeyo6r2mjhMxTWsLGFRKXVa2go3W6hlFgw3e14+BwypCV+A6WLyNvqAgSNcJX21xNwhlUE38=
  on:
    branch: master
    tags: true
    condition: "$DEPLOY = yes"
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
